name: thesis_project
description: "Thesis Project for Dyslexia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  provider: ^6.0.0
  path: ^1.8.0
  shared_preferences: ^2.0.8

  # UI dependencies
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.6

  # VOSK and Audio related
  vosk_flutter: ^0.3.48
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  path_provider: ^2.1.2

  # Utilities
  archive: ^3.4.10
  http: ^0.13.5
  string_similarity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/words.txt
    - lib/assets/sentences.txt
    - lib/assets/paragraphs.txt
    - lib/assets/pages.txt
    - lib/assets/fonts/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: lib/assets/fonts/OpenDyslexic-Regular.otf
        - asset: lib/assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: lib/assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
