name: thesis_project
description: "OpenDSA: Reading - Applicazione per assistere persone con dislessia nella lettura"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

# Dipendenze base
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  provider: ^6.0.0
  path: ^1.8.0
  shared_preferences: ^2.0.8
  crypto: ^3.0.3

  # UI dependencies
  cupertino_icons: ^1.0.8

  # VOSK and Audio related
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  permission_handler_platform_interface: ^3.12.0
  path_provider: ^2.1.2

  # Utilities
  archive: ^3.4.10
  http: ^0.13.5
  string_similarity: ^2.0.0
  collection: ^1.18.0
  json_annotation: ^4.8.1

  # Packaging dependencies
  msix: ^3.16.7
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

dependency_overrides:
  vosk_flutter:
    path: ./local_vosk_flutter

# Configurazione icone applicazione
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icon/app_icon.png"

# Configurazione Windows
msix_config:
  display_name: OpenDSA Reading
  publisher_display_name: Lorenzo De Marco
  identity_name: Lorenzo DM (LorenzoElSalserito)
  msix_version: 1.0.0.0
  logo_path: assets/icon/app_icon.png
  capabilities: internetClient, microphone

flutter:
  uses-material-design: true

  assets:
    - lib/assets/exercises/easy_words.txt
    - lib/assets/exercises/medium_words.txt
    - lib/assets/exercises/hard_words.txt
    - lib/assets/exercises/sentences.txt
    - lib/assets/exercises/paragraphs.txt
    - lib/assets/exercises/pages.txt
    - lib/assets/fonts/
    - lib/assets/icon/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: lib/assets/fonts/OpenDyslexic-Regular.otf
        - asset: lib/assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: lib/assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/OpenDyslexic-Bold-Italic.otf
          weight: 700
          style: italic